# Generated by Django 4.1.7 on 2023-02-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='songinalbum',
            name='unique_number',
        ),
        migrations.AddConstraint(
            model_name='songinalbum',
            constraint=models.UniqueConstraint(fields=('song', 'number'), name='unique_number'),
        ),
    ]
